name: Code Checkout and List Files

on: [push]

jobs:
  checkout_and_list:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Use a pre-built action to check out your repository code
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Run a command to list files in the directory
      - name: List files in repository
        run: ls -l
